### ISSUE TITLE
Rails 3.1 compatibility

### ISSUE THREAD

**Issue by dgmdan** [zdennis/ar-extensions#16]
In my Gemfile I have:
`gem 'rails', '3.1.0'
gem 'ar-extensions', :git => "git://github.com/zdennis/ar-extensions.git"`
When I do `bundle install` I get:
`Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    ar-extensions (>= 0) ruby depends on
      activerecord (~> 2.1) ruby
    rails (= 3.1.0) ruby depends on
      activerecord (3.1.0)`
Am I missing something or is the gem really not compatible with activerecord 3.1.0?  Has anyone had success using rails 3.1.0/ruby 1.9.3 with this gem?  I was using it with rails 3.0.9/ruby 1.8.7 and everything was fine.

**Comment by zdennis** [comment]
@dgmdan, you want to use https://github.com/zdennis/activerecord-import for Rails 3.x compatibility.
