### ISSUE TITLE
Postgresql Non Existant

### ISSUE THREAD

**Issue by cherring** [zdennis/ar-extensions#2]
You could mention in your README that PostgreSQL isn't supported for your import function.

**Comment by cherring** [comment]
Well maybe just not in tiny writing at the bottom :(

**Comment by wallclimber21** [comment]
From the README:

> Upcoming:
> - postgresql support for imports

I'm guessing that this is the only indication that import is not support for Postgresql? And maybe the fact that .../import/postgresql.rb is an empty file.

Not very obvious indeed and it could me quite a bit of time to figure our why it wasn't working.

For the benefit of other, can this maybe get a bit more prominence in the README?

**Comment by wallclimber21** [comment]
BTW: even without multiple-value inserts, .import is still way faster than simply looping through all the records with plain vanilla activerecord, so it's already a big help...
