### ISSUE TITLE
Rails 2.3.4 support: warning: default `to_a' will be obsolete 

### ISSUE THREAD

**Issue by rud** [zdennis/ar-extensions#6]
When using ar-extensions 0.9.2 with Rails 2.3.4 on ruby 1.8.6-1.8.7, the warning "default `to_a' will be obsolete" is often printed to STDERR.

The patch at [1] fixes this problem, please have a look.

[1] http://github.com/thillerson/ar-extensions/commit/fc0cab906ebc3766f22ab55e8e38a1c173187dbb

Regards
/Laust Rud

**Comment by ghazel** [comment]
Well, +1, I guess.

Rails won't turn off the warning, and I don't see a good way around this. The patch included above "fixes" the issue.

https://rails.lighthouseapp.com/projects/8994/tickets/5130-warning-default-to_a-will-be-obsolete-from-method_missing-in-association_proxy

**Comment by sid137** [comment]
Hi,  

```
Is there any chance of applying this patch?
```

**Comment by rud** [comment]
@sid137 think not, closing :stars:
